### ISSUE TITLE
percent sign in cookie

### ISSUE THREAD

**Issue by acodispo** [delight-im/PHP-Auth#38] opened 2017-07-22 15:57 UTC
Does auth use a non-standard way of writing the PHPSESSID cookie? I am sometimes getting a %25 (encoded `%`) in my cookie, which is causing an error to be displayed in unexpected places. Thanks!

**Comment by ocram** [comment] 2017-07-22 21:49
Yes, indeed. This library uses [this other library](https://github.com/delight-im/PHP-Cookie) for handling cookies. Whenever a session [is started](https://github.com/delight-im/PHP-Cookie/blob/abffc0d4506baf31fbe32aeb3457299d8d97c4a0/src/Session.php#L29) or [regenerated](https://github.com/delight-im/PHP-Cookie/blob/abffc0d4506baf31fbe32aeb3457299d8d97c4a0/src/Session.php#L64), the cookie for PHP's internal session ID is rewritten [like this](https://github.com/delight-im/PHP-Cookie/blob/abffc0d4506baf31fbe32aeb3457299d8d97c4a0/src/Session.php#L146).

Does that help to reproduce or track down the problem?

So you have problems with a percent sign (`%`) in the cookie's value, right? The cookie's name is fine, and is probably the default value used by PHP. Is that correct? The cookie's value probably contains only PHP's automatically generated tokens as well, though, doesn't it?

Thanks for your report!

**Comment by acodispo** [comment] 2017-07-23 16:08
Ah hah, thank you for the info! Yes, the name of the cookie is the default ("PHPSESSID"). Here's a sample of a troublesome value: `a2sYF92LvsLBu%252C8etMv762`

I've got two branches of my code, one before I started to integrate php-auth, and one using php-auth  for authentication. I'm not _positive_, but it *seems* as if the pre-auth code doesn't put `%25` in that cookie's content, whereas the code using php-auth does.

Any thoughts? Your help is deeply appreciated.

**Comment by ocram** [comment] 2017-07-23 18:57
Thanks for the additional information!

Actually, I'm really wondering how that percent sign (`%`) arrives in your session ID. Are you generating the session IDs manually? By default, PHP's session IDs will only ever contain characters from the set `[a-zA-Z0-9,-]` where `%` is not included.

Could you run the following script in the same environment for debugging and then post its output here?

```php
echo 'PHP version:';
echo "\n";
\var_dump(\phpversion());
echo "\n";

echo 'Are sessions started automatically?';
echo "\n";
\var_dump(\ini_get('session.auto_start'));
echo "\n";

if (\PHP_VERSION_ID >= 70100) {
    echo 'Length of session IDs:';
    echo "\n";
    \var_dump(\ini_get('session.sid_length'));
    echo "\n";

    echo 'Bits per character in session ID:';
    echo "\n";
    \var_dump(\ini_get('session.sid_bits_per_character'));
    echo "\n";

    echo 'Sample session ID:';
    echo "\n";
    \var_dump(\session_create_id());
    echo "\n";
}
else {
    echo 'Hash function for session ID:';
    echo "\n";
    \var_dump(\ini_get('session.hash_function'));
    echo "\n";

    echo 'Bits per character in session ID:';
    echo "\n";
    \var_dump(\ini_get('session.hash_bits_per_character'));
    echo "\n";
}

echo 'Session ID before starting session (should be empty):';
echo "\n";
\var_dump(\session_id());
echo "\n";

echo 'Default name of session (cookie):';
echo "\n";
\var_dump(\session_name());
echo "\n";

\session_name('PHPSESSID');
\session_id('a2sYF92LvsLBu%2C8etMv762');
\session_start();

echo 'Session ID after starting session (should not be empty):';
echo "\n";
\var_dump(\session_id());
echo "\n";

echo 'Custom name of session (cookie):';
echo "\n";
\var_dump(\session_name());
echo "\n";

require_once __DIR__ . '/vendor/autoload.php';
\var_dump(\Delight\Http\ResponseHeader::take('Set-Cookie'));
```

For me, the output is the following:

```
PHP version:
string(23) "7.0.18"

Are sessions started automatically?
string(1) "0"

Hash function for session ID:
string(1) "0"

Bits per character in session ID:
string(1) "5"

Session ID before starting session (should be empty):
string(0) ""

Default name of session (cookie):
string(6) "MYSESSID"


Warning: session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,'
Session ID after starting session (should not be empty):
string(24) "a2sYF92LvsLBu%2C8etMv762"

Custom name of session (cookie):
string(9) "PHPSESSID"

string(66) "Set-Cookie: PHPSESSID=a2sYF92LvsLBu%252C8etMv762; path=/; HttpOnly"

Warning: Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on line 0

Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in Unknown on line 0
```

Note the warnings, which tell you again that the percent sign is usually not part of PHP's session IDs. Ignoring the warning seems to work, judging from what can be seen above, but may provide inconsistent results, which is exactly what we have here.

Further, you can see that the percent sign has been encoded *once* in the `Set-Cookie` header printed at the end, where `%` has become `%25`.

Now if you replace

```php
\session_start();
```

in the code above with

```php
require_once __DIR__ . '/vendor/autoload.php';
\Delight\Cookie\Session::start();
```

that reproduces the behavior that is present in this library, where PHP's `Set-Cookie` header is being rewritten. And the result is, at least in my example, that the percent sign in the `Set-Cookie` header has been encoded *twice*, with `%` now shown as `%2525`.

Is this the behavior that you encountered? Why is the percent sign included in the session ID? Is there any chance it could be removed? As it's illegal, as per PHP's configuration and warnings, inconsistent behavior must be expected here.

**Comment by acodispo** [comment] 2017-07-25 18:51
AFAIK I'm just generating the session id in the default way.

The puzzling thing is that if I check out my php-auth branch, I get the `%25`. If I check out my production branch (where I haven't integrated php-auth), I don't get the illegal character.

The output of the code you suggested:

```
PHP version:
string(6) "5.6.19"

Are sessions started automatically?
string(1) "0"

Hash function for session ID:
string(1) "0"

Bits per character in session ID:
string(1) "6"

Session ID before starting session (should be empty):
string(0) ""

Default name of session (cookie):
string(9) "PHPSESSID"


Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /home/htmadmin/int.harvesttomarket.com/authDebug.php:2) in /home/htmadmin/int.harvesttomarket.com/authDebug.php on line 52

Warning: session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /home/htmadmin/int.harvesttomarket.com/authDebug.php on line 52

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/htmadmin/int.harvesttomarket.com/authDebug.php:2) in /home/htmadmin/int.harvesttomarket.com/authDebug.php on line 52
Session ID after starting session (should not be empty):
string(24) "a2sYF92LvsLBu%2C8etMv762"

Custom name of session (cookie):
string(9) "PHPSESSID"

NULL

Warning: Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on line 0

Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/tmp) in Unknown on line 0
```

Thanks again for your help with this!

**Comment by acodispo** [comment] 2017-07-25 19:30
As a very minimal example of what I'm seeing, I put the following script (test.php) on my server:

```
<?php
$host = "my-host";
$user = "db-user";
$pw = "db-password";
$database = "db-name";

require 'vendor/autoload.php';

$db = new PDO('mysql:dbname='.$database.';host='.$host.';charset=utf8mb4', $user, $pw);
$auth = new \Delight\Auth\Auth($db);

echo "The script has run.";
```

I browse to the script, & check the written cookie. If I don't see `%25` in the content, I remove the cookie, and refresh the page. Usually within 1-3 repetitions, I see the error. Output:

```
The script has run.
Warning: Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on line 0

Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/tmp) in Unknown on line 0
```

**Comment by acodispo** [comment] 2017-07-25 19:55
Just to be clear, I do see `%252C` every time. So it's the double-encryption of the `%2C` (the comma) that seems to be causing the problem.

**Comment by ocram** [comment] 2017-07-26 14:29
> Just to be clear, I do see `%252C` every time. So it's the double-encryption of the `%2C` (the comma) that seems to be causing the problem.

That's it! Thanks a lot for debugging this and tracking down the exact problem!

The crucial setting that is different between our setups is

```
# < PHP 7.1
session.hash_bits_per_character

# >= PHP 7.1
session.sid_bits_per_character
```

as displayed by the test script that I asked you to run.

While that value is `5` for me, it is `6` for you. This changes the character set that is used:

```
# 4 bits (16 characters):
[0-9a-f]

# 5 bits (32 characters):
[0-9a-v]

# 6 bits (64 characters):
[0-9a-zA-Z,-]
```

Thus the comma could never come up in my tests, but it *could* in yours.

> If I don't see `%25` in the content, I remove the cookie, and refresh the page. Usually within 1-3 repetitions, I see the error.

The reason for this behavior is now perfectly clear as well: The raw data for the session ID is somewhat random, and when encoded using the character set outlined above, the likelihood of the comma appearing in the output is roughly 34%.

The bug had to be fixed in the [cookie library](https://github.com/delight-im/PHP-Cookie) that is used: https://github.com/delight-im/PHP-Cookie/commit/a66c8a02aa4776c4b7d3d04c695411f73e04e1eb

If you're using Composer, running

```
composer update delight-im/cookie
```

in your project's root (where the `vendor` directory is) should be enough to get the fix. Otherwise, you have to re-import the `Cookie` class.

Thanks a lot for your help!

**Closed by ocram** 2017-07-26 14:29 UTC
Labels: bug

**Comment by acodispo** [comment] 2017-07-26 14:35
@ocram Wow, thank you so much! That seems to have fixed the problem. Thank you for your responsiveness on this issue & others!
