### ISSUE TITLE
issue when using "localhost"

### ISSUE THREAD

**Issue by troublete** [delight-im/PHP-Auth#1] opened 2016-07-03 13:58 UTC
I had a tiny issue when using localhost as domain.

It seemed like the parameters couldn't be pushed into a cookie. I just quickly debugged it in the "login" method. Maybe some further investigation will be necessary. 

Just wanted to let u know. 

I used it with a ordinary XAMPP stack with PHP 7 - just to make this information useful.

Great lib btw! :+1:

**Comment by mwaclawek** [comment] 2016-07-07 16:42
Thanks a lot for your report!

Unfortunately, no problems here on XAMPP with PHP 7.0.8, so cannot reproduce. Sorry!

Could you please describe what has been your issue with cookies on `localhost`?

What's wrong specifically? Are you unable to sign in? Can you try the sample application from the `tests` directory and see if things work there?

Thank you!

**Comment by troublete** [comment] 2016-07-07 16:50
Well i actually didn't investigate much further after it worked on 127.0.0.1 -- will try when i have a minute tho to give a more precise picture. 

The case looked like that, and i thought it was kinda odd, i build a "simple" signup thing where i allowed to directly verify after signup because was just for a small project where mail server wasn't necessary. And after the signup the login did "happen" - in the sense that the check immediatly after the login worked (literaly next line) -- when i redirected tho to a dashboard page the cookie wasn't set. i thought it was weird. when i checked the cookie set -- and either domain or path was set that localhost was set like ".localhost" -- where i think that after the redirect the cookie didn't apply for the page. as i said i'll look into it again.

**Comment by mwaclawek** [comment] 2016-07-07 17:14
Ah, that makes sense! Thank you!

So things were not really working on `localhost` but as soon as you switched to its equivalent `127.0.0.1`, everything was working without any changes, right?

I'm using Firefox, and `.localhost` works fine as the cookie domain. Maybe you're using some other browser where this does not work?

Looked up Chrome's behavior, and found two issues in Chrome's bug tracker:

 * https://bugs.chromium.org/p/chromium/issues/detail?id=56211
 * https://bugs.chromium.org/p/chromium/issues/detail?id=551906

From what I understood, cookies might work in Chrome if you're setting the domain to `localhost` (without the leading dot) or to an empty string. We should check that. Most importantly, we should not implement a browser switch but find one solution that works for all browsers.

In the meantime, using `127.0.0.1` is probably a good workaround. Thanks!

**Comment by troublete** [comment] 2016-07-07 17:39
Affirmative. 
I use Chrome, gimme that v8! :smile: 
No problem. Thank u for the quick response! :)
I may create a pull request, but no time atm. sorry.

**Comment by mwaclawek** [comment] 2016-07-08 23:08
Thank you so much!

Especially your observations from the second comment were really helpful.

This should have been fixed now :) Can you try? You just need to update your dependency via `composer update` since `v2.0.1` contains the fix.

**Comment by troublete** [comment] 2016-07-11 06:49
Just tried. Lookin swell! :) Good job! :+1:

**Comment by mwaclawek** [comment] 2016-07-11 12:10
Thanks!

**Closed by mwaclawek** 2016-07-11 12:10 UTC
Labels: bug
