### ISSUE TITLE
doesn't work with two installations on one domain.

### ISSUE THREAD

**Issue by glebavladimir** [delight-im/PHP-Auth#29] opened 2017-06-08 15:54 UTC
If you try to use the library on two websites sharing one domain (ex.: domain.com and sub.domain.com), after authorisation on domain.com you go to sub.domain.com and login fails every time no matter what. 
This happens when two sessions are active. If you go to the Developer Tools and remove both sessions from cookies, authorization starts working. But again until you get two sessions on both installations active again. Which happens to me quite often.

**Comment by ocram** [comment] 2017-06-08 22:23
Thanks for your feedback!

Unfortunately, we cannot reproduce this, yet. But first, let's make sure that we've got every single step of the process right.

Specifically, let's point out which protocol (HTTP vs HTTPS) and which browser (Firefox, Chrome, etc.) we're using.

 1. (In the beginning, you are signed out on both `example.com` and `sub.example.com`. Even more than that, you don't even have any session at all on both sites, which can be achieved using "private browsing" or by clearing your cookies. These statements are true for both the HTTP and HTTPS versions of both sites, if they exist.)
 1. You go to `http://example.com`.
 1. The site shows that you are not signed in yet.
 1. You enter your credentials and try to sign in.
 1. The site shows that your login has been successful.
 1. You confirm that you're still logged in after refreshing the page.
 1. You go to `http://sub.example.com`.
 1. The site shows that you are not signed in yet.
 1. You enter your credentials and try to sign in.
 1. The login attempt failed.

Is this what you did? How did the error in the last step become apparent? Was there any error message? An exception, perhaps?

For me, this fails in step 8, where `http://sub.example.com` instead shows that I'm already logged in. This is because that site picked up the session from `http://example.com`.

On the contrary, if I visit `http://sub.example.com` first, between steps 1 and 2, this prevents the site from picking up my authentication status in step 8. But logins still don't fail, I can just log in there as well.

**Comment by ocram** [comment] 2017-07-24 20:18
Closing due to inactivity

**Comment by acodispo** [comment] 2017-08-06 00:16
@ocram 

Testing in Firefox 54. HTTPS only. Using your directions above, I cannot duplicate. My results are as above.

**However**, I do see the error given the following sequence:

1. Open `https://example.com` and `https://sub.example.com` in two different browser tabs.
2. Clear cookies for `*.example.com`.
3. Switch to `example.com` tab. Site shows not signed in.
4. Enter credentials and attempt to sign in.
5. Site shows login successful.
6. Confirm login remains after refreshing page.
7. Switch to `sub.example.com` tab. Site shows not signed in.
8. *Without page refresh*, enter login credentials and attempt to sign in.
9. Login fails.

Please note that I did not refresh the page after switching to the second tab.

Please note also that when our login form is submitting, an ajax call is sent out. $auth->login() runs in the script we're using ajax to fetch, and sends back a response code to the user, telling them whether login is successful. In our case, we're seeing a success return from the ajax, then our JS refreshes the page, and the login is no longer valid.

Hope this helps! @crecent77 maybe you can follow the above process on your side and make sure this is the behavior you're seeing.

**Comment by ocram** [comment] 2017-08-08 12:03
Thanks a lot!

With your updated instructions, I was able to reproduce this problem. The crucial difference between my *suggested* steps and the steps you *actually* performed was that you didn't refresh the page in the second tab on `sub.example.com`, as far as I can see.

The fundamental reason for this problem is that there is no way to (automatically) know what scope of domains your cookies should be valid for. For that reason, the cookie specification(s) define that cookies should be valid only for the same host (exact domain match) by default. PHP uses this default setting as well. This library slightly extends the scope by accepting all subdomains as well by default.

The specific problem here then arises due to a multitude of issues that combine to some really weird behavior:

 * When you go to `example.com`, a cookie is created that is valid for `example.com` *and* all its subdomains, including `sub.example.com`, as per this library's defaults explained above.
 * You sign in, and the login state is associated with that cookie. You can refresh the `example.com` tab and you will see that the login state is kept correctly.
 * However, when switching to the `sub.example.com` tab without refreshing the displayed page, the login state is obviously not reflected on the page. It just shows the old version where you hadn't signed in yet.
 * So, as you described, you fill out the login form again and another login request is sent in the `sub.example.com` tab.
 * That login request is processed successfully.
 * **Problem 1:** For security reasons, the old session ID and session cookie are both invalidated during login and a new session ID, along with a cookie, is created.
 * **Problem 2:** The new cookie created by `sub.example.com` here is only valid for `sub.example.com` and its subdomains by default, as was the case with the other domain in the first tab.
 * Now if you go to the `example.com` tab, you will be logged out again, because the *old* session has now been invalidated and the *new* session has been created for `sub.example.com` and its subdomains only.
 * **Problem 3:** Back to the `sub.example.com` tab, a new session for `sub.example.com` has been created, but that cookie did not overwrite the old session's cookie because they differ in the domain attribute, and as such are considered different cookies.
 * So there are now *two* cookies containing a session identifier for `sub.example.com`, one being valid (the new cookie with the active session ID) and the other one being invalid (the old cookie with the session ID that has been invalidated).
 * **Problem 4:** When cookies are sent back to the server, the order is unspecified, and the server decides which session ID to pick up (again, unspecified behavior). So it appears that PHP uses the *first* session ID, which happens to be the ID for the *old* session here, which is now useless.
 * The result is that you're being logged out in the `sub.example.com` tab as well.

Does that make sense?

Long story short, you should be able to fix all that unexpected behavior by simply telling the server which hosts to serve the cookies for, so that it doesn't choose `example.com` (+ subdomains) for the first tab and `sub.example.com` (+ subdomains) for the second tab. A more reasonable setting in this specific case would probably be to set the cookies' domain to `example.com` (+ subdomains) for *both* tabs.

In order to set the cookies' domain values to a consistent value, try adding

```php
\ini_set('session.cookie_domain', '.example.com');
```

at an early point in your application, even *before* constructing the instance of `Auth`.

Does that fix the issue for you? You should try with cleared cookies again, of course. If it *does* fix the problem for you, everything is working as expected. Though this would definitely mean that the documentation is *severely* lacking some notes on this behavior. Perhaps, it should even be possible to set the domain(s) via the `Auth` constructor instead of via a PHP method or setting that is not directly related to this class.

**Comment by acodispo** [comment] 2017-08-08 23:14
That is *very* helpful, @ocram, and makes sense.

Indeed, setting `session.cookie_domain` as you suggested solves the issue for my procedure above.

Also, the result for the sequence you provide above is that if either the primary domain or the subdomain gets logged in, the other is also logged in (on refresh).

I think you've certainly pointed us in the correct direction. I clearly have some reading to do on the matter.

I think as far as php-auth goes, some notes on this behavior and links to the PHP session docs would be helpful for others who might run into this kind of thing.

Thank you!

**Comment by ocram** [comment] 2017-08-10 19:20
Thanks, glad that it works as expected!

> I think you've certainly pointed us in the correct direction. I clearly have some reading to do on the matter.

That sounds as if you are not really satisfied with the solution yet, or with how the library works. Is that correct? As far as I can see, this absolutely solves the issue. It's important to note that this method call is not a hack in any way, but a clean solution that is working as intended. It just has not been documented.

> Also, the result for the sequence you provide above is that if either the primary domain or the subdomain gets logged in, the other is also logged in (on refresh).

Is this not what you want? That is the intended behavior, because they both share the same cookie scope now. The unwanted behavior before was that the bare domain shared its cookies with the subdomain, but not the other way round. Now it's reciprocal.

The only other thing I could imagine is that you may perhaps want to restrict *every* domain to serve cookies on the *same* host only, requiring an exact domain match and never sharing cookies with any subdomains. Is that what you want instead?

> I think as far as php-auth goes, some notes on this behavior and links to the PHP session docs would be helpful for others who might run into this kind of thing.

Will definitely add a short paragraph about the default domain for cookies and about that single call to change the domain. Any other documentation about sessions should not really be required reading here. Anyway, will wait until we figured out if the current behavior and the solution is really what you want here, or if there are still some misunderstandings.

**Comment by ocram** [comment] 2017-10-21 21:26
This has been fixed now by upgrading to a new version of the cookie component used by this library. Apart from that, the handling of cookies and sessions in general has been improved, making it much more consistent and easy to understand. The README now contains extensive documentation on all the cookie attributes that you need to know.

Due to the nature of these changes, this is available in a new major version again, `v7.0.0`. For a guide on how to upgrade, please see the migration notes in `Migration.md`. That upgrade guide for this specific version may look a bit intimidating, but that’s just because these changes have to be applied with care and require precise and complete instructions. There’s not really much to change.

Thanks for your help in spotting these inconsistencies with regard to cookie handling!

**Closed by ocram** 2017-10-21 21:26 UTC
Labels: backwards-incompatible, bug
